# This is a basic workflow to help you get started with Actions

name: Workflow Run

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Manual Run"]
    branches: [main]
    types:
    - requested

env:
  GITHUB_CONTEXT: ${{ github }}

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: install deps
      run: pip install --upgrade requests pyyaml
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: run
      run: python .github/workflows/cancel.py
